### PR TITLE
python3.8 (fixes gh-192)

### LINKED ISSUE #192: Deprecation warnings in version 1.6.9, will stop working with Python 3.8
Using the current version 1.6.9., py.test spits out the following warning which indicates that PuLP will stop working with the upcoming Python version 3.8:

```
venv/lib/python3.7/site-packages/pulp/pulp.py:1672: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
    self.solutionTime += clock()
```

### PR DESCRIPTION
**Pull request by bjodah**
Should fix #192 
I ran into this problem in a dev environment where I am using python3.8 alpha:
```
   from time import clock
E   ImportError: cannot import name 'clock' from 'time' (unknown location)

/opt/cpython-master/lib/python3.8/site-packages/pulp/solvers.py:35: ImportError
```

### CODE REVIEW

**Comment by stumitchell** [comment]
Thanks
